// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wykjoxbaeyqojpbdnbgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5a2pveGJhZXlxb2pwYmRuYmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTkwNzksImV4cCI6MjA2OTI5NTA3OX0.wGysrQ_5J-vPlCIrR-f2REQ5-z9lsBpwcb5RWm2FoY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});